### ISSUE TITLE
Looks like this Argo is not as easy as ObjectMappper

### ISSUE THREAD

**Issue by alexliubj** [NicholasTD07/SwiftDailyAPI#46]
JUST FYI,

https://github.com/Hearst-DD/ObjectMapper

`class User: Mappable {
    var username: String?
    var age: Int?
    var weight: Double!
    var array: [AnyObject]?
    var dictionary: [String : AnyObject] = [:]
    var bestFriend: User?                       // Nested User object
    var friends: [User]?                        // Array of Users
    var birthday: NSDate?

```
required init?(_ map: Map) {

}

// Mappable
func mapping(map: Map) {
    username    <- map["username"]
    age         <- map["age"]
    weight      <- map["weight"]
    array       <- map["arr"]
    dictionary  <- map["dict"]
    bestFriend  <- map["best_friend"]
    friends     <- map["friends"]
    birthday    <- (map["birthday"], DateTransform())
}
```

}`

**Comment by NicholasTD07** [comment]
Thanks! I did a bit of research before starting the project with Argo being the JSON decoding framework and ObjectMapper was one of the potential frameworks that I was considering to use as the JSON decoding framework.

### About Easiness

If you are just using Argo as a framework without trying to understand how it works, it is pretty easy to use. However, if you do wish to understand how Argo decodes all the models from JSON to Swift structs/classes, it will take a while(took me about 5 - 6 hours).

### Why Argo?

I like the idea of 

> you should only be able to successfully decode an object if all parameters are satisfied properly

in Argo, which is described here with more details, https://github.com/thoughtbot/Argo/blob/master/Documentation/Ideology.md.

With Argo's implementation, if the type of a decoded value in a (partially) decoded JSON object does not match its Swift type, then it fails right away, which means, if there are more key value pairs in the JSON object need decoding, it won't be decoding all that, it just stops.

### Potential Problem While Using Argo

Though Argo is very good at what it does, there's a small problem you probably will run into while using it. Well, it's more of a Xcode problem, at least that's what happened in Xcode 6. Not too sure whether it's still the same with Xcode 7 and upcoming 7.3.

 Sometimes, when there's an error, it's really hard to
1. understand the error message
2. locate the line introducing the error

because, Argo is so functional and Swift's complier can be confused by the fact that Argo being functional in a way that the complier just gives you kind of random/not very useful error message.

The solution for this is rather than passing all the decoded values into `init` in the `decode` method like this

``` swift
extension User: Decodable {
  static func decode(j: JSON) -> Decoded<User> {
    return curry(User.init)
      <^> j <| "id"
      <*> j <| "name"
      <*> j <|? "email" // Use ? for parsing optional values
      <*> j <| "role" // Custom types that also conform to Decodable just work
      <*> j <| ["company", "name"] // Parse nested objects
      <*> j <|| "friends" // parse arrays of objects
  }
}

struct User {
  let id: Int
  let name: String
  let email: String?
  let role: Role
  let companyName: String
  let friends: [User]
}
```

having them all decoded into local `let`s, and then pass them into the `init` method. This way, you will get much meaningful errors from Swift's compiler.

``` swift
extension User: Decodable {
  static func decode(j: JSON) -> Decoded<User> {
    let id: Decoded<Int> = j <| "id"
    let name: Decoded<String> = j <| "name"

    return curry(User.init)
      <^> id
      <*> name
      // etc.
  }
}
```

I am closing this issue 'cause it's hardly an issue. But any further comments are welcome.
